name: xgboost-cell-classification-gpu
channels:
  - conda-forge
  - nvidia
  - rapidsai
dependencies:
  - python=3.10
  - py-xgboost>=1.7
  - scikit-learn>=1.1
  - scikit-optimize>=0.9
  - imbalanced-learn>=0.9
  - pandas>=1.4
  - numpy>=1.21
  - toml
  - tabulate
  - matplotlib>=3.5
  - seaborn>=0.11
  - scipy>=1.8
  - pyarrow
  - quarto
